# Generated by Django 3.2.5 on 2021-11-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSales',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=30, null=True)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('NA_sales', models.FloatField()),
                ('EU_sales', models.FloatField()),
                ('JP_sales', models.FloatField()),
                ('other_sales', models.FloatField()),
                ('global_sales', models.FloatField()),
            ],
        ),
    ]
