# Generated by Django 3.2.9 on 2021-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasales',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='datasales',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
